version: "3.7"

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d/:ro
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
#  backend:
#    depends_on:
#      - db
#    restart: on-failure
#    build: ./backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://db:3306/Snowload",
#        "spring.datasource.username" : "root",
#        "spring.datasource.password" : "password",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#  frontend:
#    depends_on:
#      - backend
#    restart: on-failure
#    build: ./frontend
#    volumes:
#      - ./frontend:/usr/app
#    ports:
#      - "3000:3000"

volumes:
  mysql-data: